### ISSUE TITLE
Server fails to start with both this mod and LuckPerms

### ISSUE THREAD

**Issue by mtulecki** [lucko/fabric-permissions-api#11]
When trying to start the server with fabric-permissions-api 0.2 and luckperms 5.4.62 it fails with the following error:
`java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'luckperms'!`
I've attached the full server log below.
Running Quilt 0.18.2 with Minecraft 1.19.3 on Ubuntu 22.04 LTS
Java info:

```
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```
[latest.log.gz](https://github.com/lucko/fabric-permissions-api/files/10872432/latest.log.gz)

**Comment by Nesquate** [comment]
`Caused by: java.lang.ClassNotFoundException: me.lucko.fabric.api.permissions.v0.OfflinePermissionCheckEvent`

Because `v0.2` version does not include latest commit ([d3c86f0](https://github.com/lucko/fabric-permissions-api/commit/d3c86f0b71a4600ee7a9ebb8c978d19c24472ab8)), you need to build manually

or wait @lucko for building `v0.3`
